config/routes.rb
ActionController::Routing::Routes.draw do |map|
  
  map.resources :grading_levels
  map.resources :ranking_levels, :collection => {:create_ranking_level=>[:get,:post], :edit_ranking_level=>[:get,:post], :update_ranking_level=>[:get,:post], :delete_ranking_level=>[:get,:post], :ranking_level_cancel=>[:get,:post], :change_priority=>[:get,:post]}
  map.resources :class_designations
  #map.resources :exam_reports, :collection => {:course_reports_index=>[:get,:post], :batch_reports_index=>[:get,:post]}
  map.resources :class_timings
  map.resources :subjects
  map.resources :attendances, :collection=>{:daily_register=>:get,:subject_wise_register=>:get}
  map.resources :employee_attendances
  map.resources :attendance_reports
  map.resources :cce_exam_categories
  map.resources :assessment_scores,:collection=>{:exam_fa_groups=>[:get],:observation_groups=>[:get]}
  map.resources :cce_settings,:collection=>{:basic=>[:get],:scholastic=>[:get],:co_scholastic=>[:get]}
  map.resources :scheduled_jobs,:except => [:show]
  map.resources :fa_groups,:collection=>{:assign_fa_groups=>[:get,:post],:new_fa_criteria=>[:get,:post],:create_fa_criteria=>[:get,:post],:edit_fa_criteria=>[:get,:post],:update_fa_criteria=>[:get,:post],:destroy_fa_criteria=>[:post],:reorder=>[:get,:post]}
  #  do |fa|
  #    fa.resources  :fa_criterias
  #  end
  map.resources :fa_criterias do |fa|
    fa.resources :descriptive_indicators do |desc|
      desc.resources :assessment_tools
    end
  end
  map.resources :observations do |obs|
    obs.resources :descriptive_indicators do |desc|
      desc.resources :assessment_tools
    end
  end
  map.resources :observation_groups,:member=>{:new_observation=>[:get,:post],:create_observation=>[:get,:post],:edit_observation=>[:get,:post],:update_observation=>[:get,:post],:destroy_observation=>[:post],:reorder=>[:get,:post]},:collection=>{:assign_courses=>[:get,:post],:set_observation_group=>[:get,:post]}
  map.resources :cce_weightages,:member=>{:assign_courses=>[:get,:post]},:collection=>{:assign_weightages=>[:get,:post]}
  map.resources :cce_grade_sets, :member=>{:new_grade=>[:get,:post],:edit_grade=>[:get,:post],:update_grade=>[:get,:post],:destroy_grade=>[:post]}

  map.feed 'courses/manage_course', :controller => 'courses' ,:action=>'manage_course'
  map.feed 'courses/manage_batches', :controller => 'courses' ,:action=>'manage_batches'
  map.resources :courses, :has_many => :batches, :collection => {:grouped_batches=>[:get,:post],:create_batch_group=>[:get,:post],:edit_batch_group=>[:get,:post],:update_batch_group=>[:get,:post],:delete_batch_group=>[:get,:post],:assign_subject_amount => [:get,:post],:edit_subject_amount => [:get,:post],:destroy_subject_amount => [:get,:post]}

  map.resources :batches, :collection=>{:batches_ajax=>[:get]} do |batch|
    batch.resources :exam_groups
    #batch.resources :additional_exam_groups
    batch.resources :elective_groups, :as => :electives
  end

  map.resources :exam_groups do |exam_group|
    exam_group.resources :exams, :member => { :save_scores => :post }
  end

  #  map.resources :additional_exam_groups do |additional_exam_group|
  #    additional_exam_group.resources :additional_exams , :member => { :save_additional_scores => :post }
  #  end

  map.resources :timetables do |timetable|
    timetable.resources :timetable_entries
  end
  map.root :controller => 'user', :action => 'login'

  map.fa_scores 'assessment_scores/exam/:exam_id/fa_group/:fa_group_id', :controller=>'assessment_scores',:action=>'fa_scores'
  map.observation_scores 'assessment_scores/batch/:batch_id/observation_group/:observation_group_id', :controller=>'assessment_scores',:action=>'observation_scores'
  map.scheduled_task 'scheduled_jobs/:job_object/:job_type',:controller => "scheduled_jobs",:action => "index"
  map.scheduled_task_object 'scheduled_jobs/:job_object',:controller => "scheduled_jobs",:action => "index"


  #map.connect 'parts/:number', :controller => 'inventory', :action => 'sho
  map.connect ':controller/:action/:id'
  map.connect ':controller/:action' 
  map.connect ':controller/:action/:id/:id2'
  map.connect ':controller/:action/:id.:format'

end

app/models/user.rb
#Fedena
#Copyright 2011 Foradian Technologies Private Limited
#
#This product includes software developed at
#Project Fedena - http://www.projectfedena.org/
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.

class User < ActiveRecord::Base
  attr_accessor :password, :role, :old_password, :new_password, :confirm_password

  validates_uniqueness_of :username, :scope=> [:is_deleted],:if=> 'is_deleted == false' #, :email
  validates_length_of     :username, :within => 1..20
  validates_length_of     :password, :within => 4..40, :allow_nil => true
  validates_format_of     :username, :with => /^[A-Z0-9_-]*$/i,
    :message => "#{t('must_contain_only_letters')}"
  validates_format_of     :email, :with => /^[A-Z0-9._%-]+@([A-Z0-9-]+\.)+[A-Z]{2,4}$/i,   :allow_blank=>true,
    :message => "#{t('must_be_a_valid_email_address')}"
  validates_presence_of   :role , :on=>:create
  validates_presence_of   :password, :on => :create

  has_and_belongs_to_many :privileges
  has_many  :user_events
  has_many  :events,:through=>:user_events
  has_one :student_record,:class_name=>"Student",:foreign_key=>"user_id"
  has_one :employee_record,:class_name=>"Employee",:foreign_key=>"user_id"

  named_scope :active, :conditions => { :is_deleted => false }
  named_scope :inactive, :conditions => { :is_deleted => true }

  def before_save
    self.salt = random_string(8) if self.salt == nil
    self.hashed_password = Digest::SHA1.hexdigest(self.salt + self.password) unless self.password.nil?
    if self.new_record?
      self.admin, self.student, self.employee = false, false, false
      self.admin    = true if self.role == 'Admin'
      self.student  = true if self.role == 'Student'
      self.employee = true if self.role == 'Employee'
      self.parent = true if self.role == 'Parent'
      self.is_first_login = true
    end
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def check_reminders
    reminders =[]
    reminders = Reminder.find(:all , :conditions => ["recipient = '#{self.id}'"])
    count = 0
    reminders.each do |r|
      unless r.is_read
        count += 1
      end
    end
    return count
  end

  def self.authenticate?(username, password)
    u = User.find_by_username username
    u.hashed_password == Digest::SHA1.hexdigest(u.salt + password)
  end

  def random_string(len)
    randstr = ""
    chars = ("0".."9").to_a + ("a".."z").to_a + ("A".."Z").to_a
    len.times { randstr << chars[rand(chars.size - 1)] }
    randstr
  end

  def role_name
    return "#{t('admin')}" if self.admin?
    return "#{t('student_text')}" if self.student?
    return "#{t('employee_text')}" if self.employee?
    return "#{t('parent')}" if self.parent?
    return nil
  end

  def role_symbols
    prv = []
    @privilge_symbols ||= privileges.map { |privilege| prv << privilege.name.underscore.to_sym }

    if admin?
      return [:admin] + prv
    elsif student?
      return [:student] + prv
    elsif employee?
      employee = employee_record
      unless employee.nil?
        if employee.subjects.present?
          prv << :subject_attendance if Configuration.get_config_value('StudentAttendanceType') == 'SubjectWise'
          prv << :subject_exam
        end
        if Batch.active.collect(&:employee_id).include?(employee.id.to_s)
          prv << :view_results
        end
      end
      return [:employee] + prv
    elsif parent?
      return [:parent] + prv
    else
      return prv
    end
  end

  def clear_menu_cache
    Rails.cache.delete("user_main_menu#{self.id}")
    Rails.cache.delete("user_autocomplete_menu#{self.id}")
  end

  def parent_record
    Student.find_by_admission_no(self.username[1..self.username.length])
  end

  def has_subject_in_batch(b)
    employee_record.subjects.collect(&:batch_id).include? b.id
  end

  def days_events(date)
    all_events=[]
    case(role_name)
    when "Admin"
      all_events=Event.find(:all,:conditions => ["? between date(events.start_date) and date(events.end_date)",date])
    when "Student"
      all_events+= events.all(:conditions=>["? between date(events.start_date) and date(events.end_date)",date])
      all_events+= student_record.batch.events.all(:conditions=>["? between date(events.start_date) and date(events.end_date)",date])
      all_events+= Event.all(:conditions=>["(? between date(events.start_date) and date(events.end_date)) and is_common = true",date])
    when "Parent"
      all_events+= events.all(:conditions=>["? between date(events.start_date) and date(events.end_date)",date])
      all_events+= parent_record.user.events.all(:conditions=>["? between date(events.start_date) and date(events.end_date)",date])
      all_events+= parent_record.batch.events.all(:conditions=>["? between date(events.start_date) and date(events.end_date)",date])
      all_events+= Event.all(:conditions=>["(? between date(events.start_date) and date(events.end_date)) and is_common = true",date])
    when "Employee"
      all_events+= events.all(:conditions=>["? between events.start_date and events.end_date",date])
      all_events+= employee_record.employee_department.events.all(:conditions=>["? between date(events.start_date) and date(events.end_date)",date])
      all_events+= Event.all(:conditions=>["(? between date(events.start_date) and date(events.end_date)) and is_exam = true",date])
      all_events+= Event.all(:conditions=>["(? between date(events.start_date) and date(events.end_date)) and is_common = true",date])
    end
    all_events
  end

  def next_event(date)
    all_events=[]
    case(role_name)
    when "Admin"
      all_events=Event.find(:all,:conditions => ["? < date(events.end_date)",date],:order=>"start_date")
    when "Student"
      all_events+= events.all(:conditions=>["? < date(events.end_date)",date])
      all_events+= student_record.batch.events.all(:conditions=>["? < date(events.end_date)",date],:order=>"start_date")
      all_events+= Event.all(:conditions=>["(? < date(events.end_date)) and is_common = true",date],:order=>"start_date")
    when "Parent"
      all_events+= events.all(:conditions=>["? < date(events.end_date)",date])
      all_events+= parent_record.user.events.all(:conditions=>["? < date(events.end_date)",date])
      all_events+= parent_record.batch.events.all(:conditions=>["? < date(events.end_date)",date],:order=>"start_date")
      all_events+= Event.all(:conditions=>["(? < date(events.end_date)) and is_common = true",date],:order=>"start_date")
    when "Employee"
      all_events+= events.all(:conditions=>["? < date(events.end_date)",date],:order=>"start_date")
      all_events+= employee_record.employee_department.events.all(:conditions=>["? < date(events.end_date)",date],:order=>"start_date")
      all_events+= Event.all(:conditions=>["(? < date(events.end_date)) and is_exam = true",date],:order=>"start_date")
      all_events+= Event.all(:conditions=>["(? < date(events.end_date)) and is_common = true",date],:order=>"start_date")
    end
    start_date=all_events.collect(&:start_date).min
    unless start_date
      return ""
    else
      next_date=(start_date.to_date<=date ? date+1.days : start_date )
      next_date
    end
  end
  def soft_delete
    self.update_attributes(:is_deleted =>true)
  end

end

app/views/user/_employee_user.erb
<%-# Fedena
#Copyright 2010 Foradian Technologies Private Limited
#
#This product includes software developed at
#Project Fedena - http://www.projectfedena.org/
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing,
#software distributed under the License is distributed on an
#"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#KIND, either express or implied.  See the License for the
#specific language governing permissions and limitations
#under the License. -%>

 <div class="label-field-pair">

<div class="text-input-bg"><%= select :user_type, :type, EmployeeDepartment.active.map {|c| [c.name, c.id]},
    {:prompt => "#{t('select_a_department')}"},
    {:onChange => "#{remote_function(:url => {:action => "list_employee_user"},
    :with => "'dept_id='+value",
        :before => "Element.show('loader')",
        :success => "Element.hide('loader')"
        )}"} %>

</div>
 </div>

app/views/user/_news_bar.html.erb
<%-# Fedena
#Copyright 2010 Foradian Technologies Private Limited
#
#This product includes software developed at
#Project Fedena - http://www.projectfedena.org/
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing,
#software distributed under the License is distributed on an
#"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#KIND, either express or implied.  See the License for the
#specific language governing permissions and limitations
#under the License. -%>

<% @dash_news = News.get_latest %>

<div id="news_bar">
  <% @dash_news.each do |news| %>
    <div class="news_box <%= "first-news" if news == @dash_news.first %>">
      <h5 class="news-title"><%= link_to shorten_string(news.title, 30), { :controller => 'news', :action => 'view', :id => news.id} %></h5>
      <small class="news-time"><%= "#{t('posted_on')}" %> <%= I18n.l(news.created_at.to_date, :format=> :date_month)  %> </small>
      <small class="comments-count"><%= link_to "#{news.comments.size} #{t('comments')}", { :controller => 'news', :action => 'view', :id => news.id, :anchor=>"comments-heading"} %></small>
    </div>
  <% end %>
</div>

app/views/user/_parent_user.erb
<%-# Fedena
#Copyright 2010 Foradian Technologies Private Limited
#
#This product includes software developed at
#Project Fedena - http://www.projectfedena.org/
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing,
#software distributed under the License is distributed on an
#"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#KIND, either express or implied.  See the License for the
#specific language governing permissions and limitations
#under the License. -%>

<div class="label-field-pair">
  <div class="text-input-bg"><%= select :batch, :batch_id,
      Batch.active.map {|c| [c.full_name, c.id]},
      {:prompt => "#{t('select_a_course')}"},
      {:onChange => "#{remote_function(:url => {:action => "list_parent_user"},
      :with => "'batch_id='+value",
      :before => "Element.show('loader')",
      :success => "Element.hide('loader')"
      )}"} %></div>
</div>

app/views/user/_users.erb
<%-# Fedena
#Copyright 2010 Foradian Technologies Private Limited
#
#This product includes software developed at
#Project Fedena - http://www.projectfedena.org/
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing,
#software distributed under the License is distributed on an
#"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#KIND, either express or implied.  See the License for the
#specific language governing permissions and limitations
#under the License. -%>

<% if @users.nil? or @users.empty? %>
  <div id="user_no_result" class="themed_text"><%= t('no_users') %></div>
<% else %>
  <div class="students-table">
    <table id="listing" align="center" width="100%" cellpadding="1" cellspacing="1">
      <tr class="tr-head">
        <td>
          <%= t('sl_no') %>
        </td>
        <td>
          <%= t('name') %>
        </td>
        <td>
        <%= t('username') %>
        </td>
        <td>
        
        </td>
      </tr>
      <tr>
        <td>

        </td>
        <td>

        </td>
        <td>

        </td>
        <td>

        </td>
      </tr>
      <% @users.each_with_index do |user,i| %>
        <tr class="tr-<%= cycle('odd', 'even') %>">
          <td class="col-1">
            <%= i+1 %>
          </td>
          <td class="col-2">
      <%=  user.full_name %>
          </td>
          <td class="col-3">
            <%= user.username %>
          </td>
          <td class="col-4">
            <%= link_to "#{t('view_profile')}", :controller => 'user', :action => 'profile', :id => user.username  %>
          </td>

        </tr>
      <% end %>
    </table>
  </div>
<% end %>

app/views/user/change_password.erb
<%-# Fedena
#Copyright 2010 Foradian Technologies Private Limited
#
#This product includes software developed at
#Project Fedena - http://www.projectfedena.org/
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing,
#software distributed under the License is distributed on an
#"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#KIND, either express or implied.  See the License for the
#specific language governing permissions and limitations
#under the License. -%>

<div id="content-header">
  <%= image_tag("/images/edit_users/edit_users_logo.jpg") %>
  <h1><%= t('edit_user') %></h1>
  <h3><%= t('update_user_information') %></h3>
  <div id="app-back-button">
    <%= link_to_function image_tag("/images/buttons/back.png",:border => 0), "history.back()" %>
  </div>
</div>

<div id="page-yield">

  <% unless flash[:notice].nil? %>
    <p class="flash-msg"> <%= flash[:notice] %> </p>
  <% end %>

  <% unless flash[:warn_notice].nil? %>
    <div id="errorExplanation" class="errorExplanation"><%= flash[:warn_notice] %> </div>
  <% end %>

  <div id="changepw-form">
    <% form_for :user do |u| %>
      <div class="box">

        <div class="label-field-pair">
          <div class="label-container"><label><%= t('old_password') %>:</label> </div>
          <div class="input-container"> <%= u.password_field :old_password %></div>
        </div>
        <div class="label-field-pair">
          <div class="label-container"><label><%= t('new_password') %>:</label> </div>
          <div class="input-container"><%= u.password_field :new_password %></div>
        </div>
        <div class="label-field-pair">
          <div class="label-container"><label><%= t('confirm_password') %> :</label> </div>
          <div class="input-container"><%= u.password_field :confirm_password %></div>
        </div>


        <%=  submit_tag "► #{t('update')}",:class=>'submit_button' %>

      <% end %>
    </div>
  </div>
</div>

app/views/user/create.erb
<%-# Fedena
#Copyright 2010 Foradian Technologies Private Limited
#
#This product includes software developed at
#Project Fedena - http://www.projectfedena.org/
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing,
#software distributed under the License is distributed on an
#"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#KIND, either express or implied.  See the License for the
#specific language governing permissions and limitations
#under the License. -%>

<div id="content-header">
  <%= image_tag("/images/user_profile/user_profile_logo.jpg") %>
  <h1><%= t('create_user') %></h1>
  <h3><%= t('make_new_admin_user') %></h3>
  <div id="app-back-button">
    <%= link_to_function image_tag("/images/buttons/back.png",:border => 0), "history.back()" %>
  </div>
</div>

<div id="page-yield">

  <% unless flash[:notice].nil? %> <p class="flash-msg"> <%= flash[:notice] %> </p> <% end %>

  <% form_for :user do |f| %>

    <%= f.error_messages %>

    <div id="create_user_form">

      <div id="necessary-field-notification"><%= t('legend1') %> <span class="necessary-field">*</span> <%= t('legend2') %>  (<%= t('only_admin_user_can_created') %>)</div>

      <div class="label-field-pair">
        <label for="user_username"><%= t('username') %><span class="necessary-field">*</span></label>
        <div class="text-input-bg"><%= f.text_field :username %></div>
      </div>

      <div class="label-field-pair">
        <label for="user_first_name"><%= t('first_name') %><span class="necessary-field">*</span></label>
        <div class="text-input-bg"><%= f.text_field :first_name %></div>
      </div>

      <div class="label-field-pair">
        <label for="user_last_name"><%= t('last_name') %></label>
        <div class="text-input-bg"><%= f.text_field :last_name %></div>
      </div>

      <div class="label-field-pair">
        <label for="user_password"><%= t('password') %> <span class="necessary-field">*</span></label>
        <div class="text-input-bg"><%= f.password_field :password %></div>
      </div>

      <div class="label-field-pair">
        <label for="user_email"><%= t('email') %> <span class="necessary-field">*</span></label>
        <div class="text-input-bg"><%= f.text_field :email %></div>
      </div>

      <%= f.hidden_field :role, :value=>'Admin' %>
      <div class="extender"></div>

      <%= submit_tag "", :value => "►#{t('create_text')}", :class => "user_submit_button" %>
      
    </div>

  <% end  %>

</div>

app/views/user/edit_privilege.html.erb
<%-# Fedena
#Copyright 2010 Foradian Technologies Private Limited
#
#This product includes software developed at
#Project Fedena - http://www.projectfedena.org/
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing,
#software distributed under the License is distributed on an
#"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#KIND, either express or implied.  See the License for the
#specific language governing permissions and limitations
#under the License. -%>


<script type="text/javascript">
  function privilege_tag_check_all_or_none(privilege_tag_id, th_is){
    field_value = th_is.checked
    $$('.privilege_check_'+privilege_tag_id).each(function(check){
      check.checked = field_value;
      if(check.checked == false){
        $(check).up('tr').removeClassName('active')
      }
      else{
        $(check).up('tr').addClassName('active')
      }
    })
  }

  function privilege_check(privilege_tag_id, th_is){
    if(th_is.checked == false){
      $$('.check_all_'+privilege_tag_id).first().checked = false
      $(th_is).up('tr').removeClassName('active')
    }
    else
    {
      $(th_is).up('tr').addClassName('active')
      var flag =0;
      $$('.privilege_check_'+privilege_tag_id).each(function(check){
        if(check.checked == false){
          flag=1;
        }
      });
      if(flag==0)
      {
        $$('.check_all_'+privilege_tag_id).first().checked = true
      }
    }
  }
</script>
<div id="content-header">
  <%= image_tag("/images/user_profile/user_profile_logo.jpg") %>
  <h1><%= t('user_privilege') %></h1>
  <h3><%= t('edit_privilege_text') %></h3>
  <div id="app-back-button">
    <%= link_to_function image_tag("/images/buttons/back.png",:border => 0), "history.back()" %>
  </div>
</div>



<div id="page-yield">

  <div class="privileges">
    <% form_for :user do |form| %>
      <div class="privilege_heading" id="application-list">
        <div class="label_field_pair"><label><%= t('set_privilege_for') %> <%= @user.full_name.capitalize %></label></div>
        <div class="user_submit_button1">
          <%= submit_tag "", :name => "commit", :value => "► #{t('save')}" %>
        </div>
      </div>
      <div class="all_privileges_list">
        <table width="100%" align="center" cellspacing="1" cellpadding="1" class="table_design">
          <tr>
            <% @privilege_tags.each_with_index do |privilege_tag,ind| %>
              <% all_privileges = privilege_tag.privileges.all(:order=>"priority ASC") %>
              <% if all_privileges.count > 0 %>
                <% if ind==0 or ind==1 or ind==4 %>
                  <td>
                  <% end %>
                  <table id="listing" align="center" width="300px" class="privilege_table" cellpadding="1" cellspacing="1">
                    <tr class="tr-head">
                      <td><%= check_box_tag "check_all", nil, false, {:class=>"check_all_#{privilege_tag.id}", :onChange=>"privilege_tag_check_all_or_none('#{privilege_tag.id}',this);" } %></td>
                      <td><%= t(privilege_tag.name_tag) %></td>
                    </tr>
                    <tr class="tr-blank"></tr>
                    <% all_privileges.each do |privilege| %>
                      <%  if @hr.blank?  %>
                        <% if privilege.name =="HrBasics" or  privilege.name =="EmployeeAttendance" or privilege.name =="PayslipPowers" or privilege.name =="EmployeeSearch" %>
                          <% next %>
                        <% end %>
                      <% end %>
                      <%  if @finance.blank?  %>
                        <% if privilege.name =="FinanceControl" %>
                          <% next %>
                        <% end %>
                      <% end %>

                      <% if privilege.name =="SMSManagement" %>
                        <% if  @sms_setting==true %>
                          <tr class="tr-<%= cycle('odd', 'even') %>">
                            <td class="col-8"><%= check_box_tag "user[privilege_ids][]", privilege.id, @user_privileges.include?(privilege),{:class=>"privilege_check_#{privilege_tag.id}", :onChange=>"privilege_check('#{privilege_tag.id}', this)", :id=>"privilege_check_#{privilege.id}"}%></td>
                            <td class="col-9"><%= t(privilege.description) %> </td>
                          </tr>
                          <script type="text/javascript">
                            privilege_check('<%= privilege_tag.id  %>', $("privilege_check_<%=privilege.id%>"))
                          </script>
                        <% end %>
                        <% next %>
                      <% end %>
                      <tr class="tr-<%= cycle('odd', 'even') %>">
                        <td class="col-8"><%= check_box_tag "user[privilege_ids][]", privilege.id, @user_privileges.include?(privilege),{:class=>"privilege_check_#{privilege_tag.id}", :onChange=>"privilege_check('#{privilege_tag.id}', this)", :id=>"privilege_check_#{privilege.id}"}%></td>
                        <td class="col-9"><%= t(privilege.description) %> </td>
                      </tr>
                      <script type="text/javascript">
                        privilege_check('<%= privilege_tag.id  %>', $("privilege_check_<%=privilege.id%>"))
                      </script>
                    <% end %>
                  </table>
                  <% if ind==0 or ind==3 or ind==4 %>
                  </td>
                <% end %>
              <% end %>
            <% end %>
          </tr>
        </table>
      </div>
    <% end %>
  </div>
</div>